# Generated by Django 3.1.4 on 2021-05-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='visits',
        ),
    ]
